{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.dovehome",
    "module": "bakalib-common-1.19.2",
    "version": "1.0.0.0-a3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "6.5.85"
          }
        }
      ],
      "files": [
        {
          "name": "bakalib-common-1.19.2-1.0.0.0-a3.jar",
          "url": "bakalib-common-1.19.2-1.0.0.0-a3.jar",
          "size": 3027,
          "sha512": "4e7f3a90adfcb00b8f32d3a4ce733a00f84532f130fa62ad2f9c68cb04638fe918499336b72fa87eb92f7104bd968adf58c62628c143f555b06a33cd49be6c4b",
          "sha256": "7953d05891c105a31dad29d7466561b9f8560dc0880cac4d4fddd0bc185a745b",
          "sha1": "94d19feaaff9ec6754ccaf59c525f2d2909c0cd3",
          "md5": "3a9423cf3c4bf98011e123de8f61ee9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "6.5.85"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "bakalib-common-1.19.2-1.0.0.0-a3.jar",
          "url": "bakalib-common-1.19.2-1.0.0.0-a3.jar",
          "size": 3027,
          "sha512": "4e7f3a90adfcb00b8f32d3a4ce733a00f84532f130fa62ad2f9c68cb04638fe918499336b72fa87eb92f7104bd968adf58c62628c143f555b06a33cd49be6c4b",
          "sha256": "7953d05891c105a31dad29d7466561b9f8560dc0880cac4d4fddd0bc185a745b",
          "sha1": "94d19feaaff9ec6754ccaf59c525f2d2909c0cd3",
          "md5": "3a9423cf3c4bf98011e123de8f61ee9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bakalib-common-1.19.2-1.0.0.0-a3-sources.jar",
          "url": "bakalib-common-1.19.2-1.0.0.0-a3-sources.jar",
          "size": 2829,
          "sha512": "79e50bfb08cefcc3774060537dab439c23fc18408aeabe5169acc4fb6e8a8c258b9d4537deca87e79ddeca03969e95260fb1bb9f4c7af6d8a5136fdacee6c05c",
          "sha256": "4c72bb02095bdd6f016a96f1f769b5cb3e7fef4ade572c79c1683ad4b417aebe",
          "sha1": "ada601bd19ec712e062eeaad3325c4c3705c26b6",
          "md5": "f8707f81bc0fd3ae3c74f881e7311bca"
        }
      ]
    }
  ]
}
